package com.lucasjwilber.freenote.viewmodels

import android.app.Application
import android.util.Log
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.LiveData
import com.lucasjwilber.freenote.NOTE
import com.lucasjwilber.freenote.database.NoteDao
import com.lucasjwilber.freenote.database.NoteDatabase
import com.lucasjwilber.freenote.database.NoteRepository
import com.lucasjwilber.freenote.models.Note
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch
import java.util.*

abstract class BaseViewModel(application: Application): AndroidViewModel(application)  {
    private val noteRepository: NoteRepository
    var noteLiveData: LiveData<Note>? = null
    var noteNeedsToBeSaved: Boolean = false
    //todo: rename to something more descriptive eg "segmentGetsFocus"
    var titleHasBeenSet: Boolean = false

    open var note: Note = Note(
        null,
        NOTE,
        "",
        "",
        Date().time
    )


    init {
        val noteDao: NoteDao = NoteDatabase.getDatabase(application).noteDao()
        // application context is passed to the repository for shared preferences access
        noteRepository =
            NoteRepository(
                noteDao,
                application
            )
    }


    fun getNote(noteId: Long) {
        this.noteLiveData = noteRepository.getNoteById(noteId)
    }


    fun saveNote() {

        Log.i("ljw", "saving note ${note.id}")
        GlobalScope.launch(Dispatchers.IO) {
            if (note.id == null) { // save a new note
                // insert returns the autogenerated id
                note.id = noteRepository.insert(note)
            } else {
                noteRepository.update(note)
            }
            //todo: set flag to show delete option now
            //todo: showToast(this, getString(R.string.saved))
        }
    }


    fun deleteNote() {
        if (noteLiveData?.value?.id != null) {
            GlobalScope.launch(Dispatchers.IO) {
                Log.i("ljw", "deleting note " + noteLiveData?.value?.id)
                noteRepository.deleteNoteById(noteLiveData?.value?.id!!)
            }
        }
    }
}